name: Ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install & configure poetry
      run: |
        python -m pip install poetry==1.4.2
        python -m poetry config virtualenvs.in-project true
    - name: Install poetry dependencies
      run: |
        python -m poetry install

    - name: Lint
      run: |
        python -m poetry run make lint
    - name: Test
      run: |
        python -m poetry run make test

  Release:
    needs: Quality
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Python Semantic Release needs access to the full history to determine whether a release should be made.
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install & configure poetry
        env:
            PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install poetry==1.4.2
          python -m poetry config virtualenvs.in-project true
          python -m poetry config pypi-token.pypi "$PYPI_API_TOKEN"

      - name: Install poetry dependencies
        run: |
          python -m poetry install

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Build
        run: |
          python -m poetry build

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m poetry run semantic-release --verbose publish
