name: Ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install & configure poetry
      run: |
        python -m pip install poetry==1.4.2
        python -m poetry config virtualenvs.in-project true
    - name: Install poetry dependencies
      run: |
        python -m poetry install

    - name: Lint
      run: |
        python -m poetry run make lint
    - name: Test
      run: |
        python -m poetry run make test

  Release:
    needs: Quality
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install & configure poetry
        run: |
          python -m pip install poetry==1.4.2
          python -m poetry config virtualenvs.in-project true
      - name: Install poetry dependencies
        run: |
          python -m poetry install

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-
      - name: Install node packages
        run: |
          npm install

      - name: Git Configure
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Publish
        run: |
          poetry run semantic-release publish
