name: Lint and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install & configure poetry
      run: |
        python -m pip install poetry==1.4.2
        python -m poetry config virtualenvs.in-project true

    - name: Cache poetry virtualenv
      uses: actions/cache@v2
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

    - name: Install poetry dependencies
      run: |
        python -m poetry install

    - name: Lint
      run: |
        python -m poetry run make lint

    - name: Test
      run: |
        python -m poetry run make test
